/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package client;

/**
 *
 * @author saadrady
 */
public class BoardPanel extends javax.swing.JPanel {

    /**
     * Creates new form BoardPanel
     */
    public BoardPanel() {
        initComponents();
        addLocalModeButton();
    }

    /**
     * Adds the "Local 2-player" option below Start Game (kept outside the generated code
     * so the NetBeans form editor doesn't drop it). Both players share this device and window.
     */
    private void addLocalModeButton() {
        javax.swing.JButton localButton = new javax.swing.JButton("Local 2-player (same device)");
        localButton.setBackground(new java.awt.Color(255, 255, 255));
        localButton.setFont(new java.awt.Font("Arial", 1, 14));
        localButton.setForeground(new java.awt.Color(0, 0, 0));
        localButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                javax.swing.JFrame frame = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(BoardPanel.this);
                LocalGame.start(frame);
            }
        });
        add(localButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 450, 206, 40));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(30, 30, 60));
        setPreferredSize(new java.awt.Dimension(8, 300));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 215, 0));
        jLabel1.setText("Backgammon");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 80, 318, 60));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter your name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 280, 132, 25));

        jTextField1.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 315, 126, 35));

        jButton1.setBackground(new java.awt.Color(255, 215, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Start Game");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 390, 115, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String playerName = jTextField1.getText();
    
    if (playerName.trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter your name!");
        return;
    }
    if (playerName.trim().length() < 3) {
    javax.swing.JOptionPane.showMessageDialog(this, "Name must be at least 3 characters!");
    return;
}
    
    String serverIP = javax.swing.JOptionPane.showInputDialog(this, "Enter server IP:", ClientConfig.getHost());
    if (serverIP == null) return;
    
    serverIP = serverIP.trim();

    // Validate IP / hostname format (localhost, IPv4 address or a host name such as an EC2 public DNS)
    if (!serverIP.matches("^(localhost|\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?(\\.[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?)+)$")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Invalid IP address!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    javax.swing.JFrame frame = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
    frame.getContentPane().removeAll();
    frame.getContentPane().setLayout(new java.awt.BorderLayout());
    
    GamePanel gamePanel = new GamePanel();
    frame.getContentPane().add(gamePanel, java.awt.BorderLayout.CENTER);
    frame.setTitle("Waiting for opponent...");
    frame.revalidate();
    frame.repaint();

    // Block board input while waiting (the window itself stays responsive)
    java.awt.Component previousGlassPane = frame.getGlassPane();
    frame.setGlassPane(createWaitingOverlay());
    frame.getGlassPane().setVisible(true);

    final String host = serverIP;
    // Connecting blocks until the server pairs us with an opponent, so do it off the Swing UI thread
    new javax.swing.SwingWorker<GameClient, Void>() {
        @Override
        protected GameClient doInBackground() {
            return new GameClient(host, gamePanel);
        }

        @Override
        protected void done() {
            frame.getGlassPane().setVisible(false);
            frame.setGlassPane(previousGlassPane);
            GameClient client = null;
            try {
                client = get();
            } catch (Exception e) {
                System.out.println("Connection failed: " + e.getMessage());
            }
            if (client != null && client.getPlayerNumber() != 0) {
                gamePanel.setPlayerNumber(client.getPlayerNumber());
                gamePanel.setGameClient(client);
                frame.setTitle("Backgammon - White's Turn ⚪");
                frame.revalidate();
                frame.repaint();
            } else {
                javax.swing.JOptionPane.showMessageDialog(frame, 
                    "Could not connect to server!\nCheck the IP address.", 
                    "Connection Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                frame.setTitle("Backgammon Game");
                frame.getContentPane().removeAll();
                frame.getContentPane().add(new BoardPanel());
                frame.revalidate();
                frame.repaint();
            }
        }
    }.execute();


    }//GEN-LAST:event_jButton1ActionPerformed


    /**
     * Semi-transparent overlay shown while waiting for an opponent; it swallows
     * mouse clicks so the board can't be used before the server assigns a side.
     */
    private static javax.swing.JComponent createWaitingOverlay() {
        javax.swing.JPanel overlay = new javax.swing.JPanel(new java.awt.GridBagLayout()) {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                g.setColor(new java.awt.Color(0, 0, 0, 120));
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        overlay.setOpaque(false);
        javax.swing.JLabel label = new javax.swing.JLabel("Waiting for opponent...");
        label.setForeground(java.awt.Color.WHITE);
        label.setFont(new java.awt.Font("Helvetica Neue", java.awt.Font.BOLD, 24));
        overlay.add(label);
        overlay.addMouseListener(new java.awt.event.MouseAdapter() { });
        overlay.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() { });
        return overlay;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
