/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package client;

/**
 *
 * @author saadrady
 */
public class GamePanel extends javax.swing.JPanel {
    
    private int selectedPoint = -1; // المثلث المختار
    private int[] currentDice = {0, 0}; // النرد الحالي
    private game.BackgammonBoard board = new game.BackgammonBoard();

    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        point19 = new javax.swing.JLabel();
        point20 = new javax.swing.JLabel();
        point21 = new javax.swing.JLabel();
        point22 = new javax.swing.JLabel();
        point23 = new javax.swing.JLabel();
        point24 = new javax.swing.JLabel();
        point6 = new javax.swing.JLabel();
        point5 = new javax.swing.JLabel();
        point4 = new javax.swing.JLabel();
        point3 = new javax.swing.JLabel();
        point2 = new javax.swing.JLabel();
        point1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        point14 = new javax.swing.JLabel();
        point15 = new javax.swing.JLabel();
        point16 = new javax.swing.JLabel();
        point17 = new javax.swing.JLabel();
        point18 = new javax.swing.JLabel();
        point12 = new javax.swing.JLabel();
        point11 = new javax.swing.JLabel();
        point10 = new javax.swing.JLabel();
        point9 = new javax.swing.JLabel();
        point8 = new javax.swing.JLabel();
        point7 = new javax.swing.JLabel();
        point13 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(92, 61, 30));
        setToolTipText("255");
        setLayout(null);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 215, 0));
        jLabel7.setText("13");
        add(jLabel7);
        jLabel7.setBounds(50, 2, 42, 17);

        jPanel3.setBackground(new java.awt.Color(46, 125, 50));
        jPanel3.setLayout(null);

        point19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_black_5.png"))); // NOI18N
        jPanel3.add(point19);
        point19.setBounds(5, 0, 70, 250);

        point20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_0.png"))); // NOI18N
        jPanel3.add(point20);
        point20.setBounds(78, 0, 70, 250);

        point21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_white_0.png"))); // NOI18N
        jPanel3.add(point21);
        point21.setBounds(151, 0, 70, 250);

        point22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_0.png"))); // NOI18N
        jPanel3.add(point22);
        point22.setBounds(224, 0, 70, 250);

        point23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_white_0.png"))); // NOI18N
        jPanel3.add(point23);
        point23.setBounds(297, 0, 70, 250);

        point24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_2.png"))); // NOI18N
        jPanel3.add(point24);
        point24.setBounds(370, 0, 70, 250);

        point6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_5_flipped.png"))); // NOI18N
        jPanel3.add(point6);
        point6.setBounds(5, 410, 70, 250);

        point5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_white_0_flipped.png"))); // NOI18N
        jPanel3.add(point5);
        point5.setBounds(78, 410, 70, 250);

        point4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_0_flipped.png"))); // NOI18N
        jPanel3.add(point4);
        point4.setBounds(151, 410, 70, 250);

        point3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_white_0_flipped.png"))); // NOI18N
        jPanel3.add(point3);
        point3.setBounds(224, 410, 70, 250);

        point2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_0_flipped.png"))); // NOI18N
        jPanel3.add(point2);
        point2.setBounds(297, 410, 70, 250);

        point1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_black_2_flipped.png"))); // NOI18N
        jPanel3.add(point1);
        point1.setBounds(370, 410, 70, 250);

        add(jPanel3);
        jPanel3.setBounds(530, 20, 455, 660);

        jLabel26.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 215, 0));
        jLabel26.setText("14");
        add(jLabel26);
        jLabel26.setBounds(123, 2, 42, 17);

        jPanel1.setBackground(new java.awt.Color(46, 125, 50));
        jPanel1.setLayout(null);

        point14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_0.png"))); // NOI18N
        jPanel1.add(point14);
        point14.setBounds(78, 0, 70, 250);

        point15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_white_0.png"))); // NOI18N
        jPanel1.add(point15);
        point15.setBounds(151, 0, 70, 250);

        point16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_0.png"))); // NOI18N
        jPanel1.add(point16);
        point16.setBounds(224, 0, 70, 250);

        point17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_black_3.png"))); // NOI18N
        jPanel1.add(point17);
        point17.setBounds(297, 0, 70, 250);

        point18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_0.png"))); // NOI18N
        jPanel1.add(point18);
        point18.setBounds(370, 0, 70, 250);

        point12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_black_5_flipped.png"))); // NOI18N
        jPanel1.add(point12);
        point12.setBounds(5, 410, 70, 250);

        point11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_white_0_flipped.png"))); // NOI18N
        jPanel1.add(point11);
        point11.setBounds(78, 410, 70, 250);

        point10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_0_flipped.png"))); // NOI18N
        jPanel1.add(point10);
        point10.setBounds(151, 410, 70, 250);

        point9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_white_0_flipped.png"))); // NOI18N
        jPanel1.add(point9);
        point9.setBounds(224, 410, 70, 250);

        point8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_3_flipped.png"))); // NOI18N
        jPanel1.add(point8);
        point8.setBounds(297, 410, 70, 250);

        point7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_white_0_flipped.png"))); // NOI18N
        jPanel1.add(point7);
        point7.setBounds(370, 410, 70, 250);

        point13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_white_5.png"))); // NOI18N
        jPanel1.add(point13);
        point13.setBounds(5, 0, 70, 250);

        jLabel28.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 215, 0));
        jLabel28.setText("16");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(269, 2, 42, 17);

        add(jPanel1);
        jPanel1.setBounds(20, 20, 455, 660);

        jLabel27.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 215, 0));
        jLabel27.setText("15");
        add(jLabel27);
        jLabel27.setBounds(196, 2, 42, 17);

        jLabel29.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 215, 0));
        jLabel29.setText("16");
        add(jLabel29);
        jLabel29.setBounds(269, 2, 42, 17);

        jLabel30.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 215, 0));
        jLabel30.setText("18");
        add(jLabel30);
        jLabel30.setBounds(415, 2, 42, 17);

        jLabel32.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 215, 0));
        jLabel32.setText("17");
        add(jLabel32);
        jLabel32.setBounds(342, 2, 42, 17);

        jLabel31.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 215, 0));
        jLabel31.setText("12");
        add(jLabel31);
        jLabel31.setBounds(50, 685, 42, 17);

        jLabel33.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 215, 0));
        jLabel33.setText("11");
        add(jLabel33);
        jLabel33.setBounds(123, 685, 42, 17);

        jLabel34.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 215, 0));
        jLabel34.setText("10");
        add(jLabel34);
        jLabel34.setBounds(196, 685, 42, 17);

        jLabel35.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 215, 0));
        jLabel35.setText("9");
        add(jLabel35);
        jLabel35.setBounds(269, 685, 42, 17);

        jLabel36.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 215, 0));
        jLabel36.setText("8");
        jLabel36.setToolTipText("");
        add(jLabel36);
        jLabel36.setBounds(342, 685, 42, 17);

        jLabel37.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 215, 0));
        jLabel37.setText("7");
        add(jLabel37);
        jLabel37.setBounds(415, 685, 42, 17);

        jLabel38.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 215, 0));
        jLabel38.setText("6");
        add(jLabel38);
        jLabel38.setBounds(565, 685, 42, 17);

        jLabel39.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 215, 0));
        jLabel39.setText("5");
        add(jLabel39);
        jLabel39.setBounds(638, 685, 42, 17);

        jLabel40.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 215, 0));
        jLabel40.setText("4");
        add(jLabel40);
        jLabel40.setBounds(711, 685, 42, 17);

        jLabel41.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 215, 0));
        jLabel41.setText("3");
        add(jLabel41);
        jLabel41.setBounds(784, 685, 42, 17);

        jLabel42.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 215, 0));
        jLabel42.setText("2");
        add(jLabel42);
        jLabel42.setBounds(857, 685, 42, 17);

        jLabel43.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 215, 0));
        jLabel43.setText("1");
        add(jLabel43);
        jLabel43.setBounds(930, 685, 42, 17);

        jLabel44.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 215, 0));
        jLabel44.setText("24");
        add(jLabel44);
        jLabel44.setBounds(930, 2, 42, 17);

        jLabel45.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 215, 0));
        jLabel45.setText("23");
        add(jLabel45);
        jLabel45.setBounds(857, 2, 42, 17);

        jLabel46.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 215, 0));
        jLabel46.setText("22");
        add(jLabel46);
        jLabel46.setBounds(784, 2, 42, 17);

        jLabel47.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 215, 0));
        jLabel47.setText("21");
        add(jLabel47);
        jLabel47.setBounds(711, 2, 42, 17);

        jLabel48.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 215, 0));
        jLabel48.setText("20");
        add(jLabel48);
        jLabel48.setBounds(638, 2, 42, 17);

        jLabel51.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText(" 0 - 0");
        add(jLabel51);
        jLabel51.setBounds(478, 300, 60, 30);

        jLabel49.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 215, 0));
        jLabel49.setText("19");
        add(jLabel49);
        jLabel49.setBounds(565, 2, 42, 17);

        jPanel2.setBackground(new java.awt.Color(74, 40, 16));
        jPanel2.setLayout(null);

        jButton2.setBackground(new java.awt.Color(255, 215, 0));
        jButton2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("ٍRD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(0, 320, 49, 30);

        add(jPanel2);
        jPanel2.setBounds(478, 20, 50, 660);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        game.BackgammonBoard board = new game.BackgammonBoard();
int[] dice = board.rollDice();
jLabel51.setText(" " + dice[0] + " - " + dice[1]);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel point1;
    private javax.swing.JLabel point10;
    private javax.swing.JLabel point11;
    private javax.swing.JLabel point12;
    private javax.swing.JLabel point13;
    private javax.swing.JLabel point14;
    private javax.swing.JLabel point15;
    private javax.swing.JLabel point16;
    private javax.swing.JLabel point17;
    private javax.swing.JLabel point18;
    private javax.swing.JLabel point19;
    private javax.swing.JLabel point2;
    private javax.swing.JLabel point20;
    private javax.swing.JLabel point21;
    private javax.swing.JLabel point22;
    private javax.swing.JLabel point23;
    private javax.swing.JLabel point24;
    private javax.swing.JLabel point3;
    private javax.swing.JLabel point4;
    private javax.swing.JLabel point5;
    private javax.swing.JLabel point6;
    private javax.swing.JLabel point7;
    private javax.swing.JLabel point8;
    private javax.swing.JLabel point9;
    // End of variables declaration//GEN-END:variables
}
