/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package client;

/**
 *
 * @author saadrady
 */
public class GamePanel extends javax.swing.JPanel {
    
    private int selectedPoint = -1; // المثلث المختار
    private int[] currentDice = {0, 0}; // النرد الحالي
    private game.BackgammonBoard board = new game.BackgammonBoard();
    private javax.swing.JLabel selectedLabel = null;
    private int selectedPointIndex = -1;
    private boolean diceRolled = false;
    private GameClient gameClient;

    
    // ألوان المثلثات (24 مثلث)
private String[] triColors = {
    "red","white","red","white","red","white",   // 1-6 تحت يمين
    "red","white","red","white","red","white",   // 7-12 تحت يسار
    "red","white","red","white","red","white",   // 13-18 فوق يسار
    "red","white","red","white","red","white"    // 19-24 فوق يمين
};
// هل المثلث معكوس؟
private boolean[] flippedPoints = {
    true,true,true,true,true,true,     // 1-6 تحت
    true,true,true,true,true,true,     // 7-12 تحت
    false,false,false,false,false,false, // 13-18 فوق
    false,false,false,false,false,false  // 19-24 فوق
};

    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        point19 = new javax.swing.JLabel();
        point20 = new javax.swing.JLabel();
        point21 = new javax.swing.JLabel();
        point22 = new javax.swing.JLabel();
        point23 = new javax.swing.JLabel();
        point24 = new javax.swing.JLabel();
        point6 = new javax.swing.JLabel();
        point5 = new javax.swing.JLabel();
        point4 = new javax.swing.JLabel();
        point3 = new javax.swing.JLabel();
        point2 = new javax.swing.JLabel();
        point1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        point14 = new javax.swing.JLabel();
        point15 = new javax.swing.JLabel();
        point16 = new javax.swing.JLabel();
        point17 = new javax.swing.JLabel();
        point18 = new javax.swing.JLabel();
        point12 = new javax.swing.JLabel();
        point11 = new javax.swing.JLabel();
        point10 = new javax.swing.JLabel();
        point9 = new javax.swing.JLabel();
        point8 = new javax.swing.JLabel();
        point7 = new javax.swing.JLabel();
        point13 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        barLabel1 = new javax.swing.JLabel();
        barLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(92, 61, 30));
        setToolTipText("255");
        setLayout(null);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 215, 0));
        jLabel7.setText("13");
        add(jLabel7);
        jLabel7.setBounds(50, 2, 42, 17);

        jPanel3.setBackground(new java.awt.Color(46, 125, 50));
        jPanel3.setLayout(null);

        point19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_black_5.png"))); // NOI18N
        point19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point19MouseClicked(evt);
            }
        });
        jPanel3.add(point19);
        point19.setBounds(5, 0, 70, 250);

        point20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_0.png"))); // NOI18N
        point20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point20MouseClicked(evt);
            }
        });
        jPanel3.add(point20);
        point20.setBounds(78, 0, 70, 250);

        point21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_white_0.png"))); // NOI18N
        point21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point21MouseClicked(evt);
            }
        });
        jPanel3.add(point21);
        point21.setBounds(151, 0, 70, 250);

        point22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_0.png"))); // NOI18N
        point22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point22MouseClicked(evt);
            }
        });
        jPanel3.add(point22);
        point22.setBounds(224, 0, 70, 250);

        point23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_white_0.png"))); // NOI18N
        point23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point23MouseClicked(evt);
            }
        });
        jPanel3.add(point23);
        point23.setBounds(297, 0, 70, 250);

        point24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_2.png"))); // NOI18N
        point24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point24MouseClicked(evt);
            }
        });
        jPanel3.add(point24);
        point24.setBounds(370, 0, 70, 250);

        point6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_5_flipped.png"))); // NOI18N
        point6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point6MouseClicked(evt);
            }
        });
        jPanel3.add(point6);
        point6.setBounds(5, 410, 70, 250);

        point5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_white_0_flipped.png"))); // NOI18N
        point5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point5MouseClicked(evt);
            }
        });
        jPanel3.add(point5);
        point5.setBounds(78, 410, 70, 250);

        point4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_0_flipped.png"))); // NOI18N
        point4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point4MouseClicked(evt);
            }
        });
        jPanel3.add(point4);
        point4.setBounds(151, 410, 70, 250);

        point3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_white_0_flipped.png"))); // NOI18N
        point3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point3MouseClicked(evt);
            }
        });
        jPanel3.add(point3);
        point3.setBounds(224, 410, 70, 250);

        point2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_0_flipped.png"))); // NOI18N
        point2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point2MouseClicked(evt);
            }
        });
        jPanel3.add(point2);
        point2.setBounds(297, 410, 70, 250);

        point1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_black_2_flipped.png"))); // NOI18N
        point1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point1MouseClicked(evt);
            }
        });
        jPanel3.add(point1);
        point1.setBounds(370, 410, 70, 250);

        add(jPanel3);
        jPanel3.setBounds(530, 20, 455, 660);

        jLabel26.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 215, 0));
        jLabel26.setText("14");
        add(jLabel26);
        jLabel26.setBounds(123, 2, 42, 17);

        jPanel1.setBackground(new java.awt.Color(46, 125, 50));
        jPanel1.setLayout(null);

        point14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_0.png"))); // NOI18N
        point14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point14MouseClicked(evt);
            }
        });
        jPanel1.add(point14);
        point14.setBounds(78, 0, 70, 250);

        point15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_white_0.png"))); // NOI18N
        point15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point15MouseClicked(evt);
            }
        });
        jPanel1.add(point15);
        point15.setBounds(151, 0, 70, 250);

        point16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_0.png"))); // NOI18N
        point16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point16MouseClicked(evt);
            }
        });
        jPanel1.add(point16);
        point16.setBounds(224, 0, 70, 250);

        point17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_black_3.png"))); // NOI18N
        point17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point17MouseClicked(evt);
            }
        });
        jPanel1.add(point17);
        point17.setBounds(297, 0, 70, 250);

        point18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_0.png"))); // NOI18N
        point18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point18MouseClicked(evt);
            }
        });
        jPanel1.add(point18);
        point18.setBounds(370, 0, 70, 250);

        point12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_black_5_flipped.png"))); // NOI18N
        point12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point12MouseClicked(evt);
            }
        });
        jPanel1.add(point12);
        point12.setBounds(5, 410, 70, 250);

        point11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_white_0_flipped.png"))); // NOI18N
        point11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point11MouseClicked(evt);
            }
        });
        jPanel1.add(point11);
        point11.setBounds(78, 410, 70, 250);

        point10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_0_flipped.png"))); // NOI18N
        point10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point10MouseClicked(evt);
            }
        });
        jPanel1.add(point10);
        point10.setBounds(151, 410, 70, 250);

        point9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_white_0_flipped.png"))); // NOI18N
        point9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point9MouseClicked(evt);
            }
        });
        jPanel1.add(point9);
        point9.setBounds(224, 410, 70, 250);

        point8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_3_flipped.png"))); // NOI18N
        point8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point8MouseClicked(evt);
            }
        });
        jPanel1.add(point8);
        point8.setBounds(297, 410, 70, 250);

        point7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_white_0_flipped.png"))); // NOI18N
        point7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point7MouseClicked(evt);
            }
        });
        jPanel1.add(point7);
        point7.setBounds(370, 410, 70, 250);

        point13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_white_5.png"))); // NOI18N
        point13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                point13MouseClicked(evt);
            }
        });
        jPanel1.add(point13);
        point13.setBounds(5, 0, 70, 250);

        jLabel28.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 215, 0));
        jLabel28.setText("16");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(269, 2, 42, 17);

        add(jPanel1);
        jPanel1.setBounds(20, 20, 455, 660);

        jLabel27.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 215, 0));
        jLabel27.setText("15");
        add(jLabel27);
        jLabel27.setBounds(196, 2, 42, 17);

        jLabel29.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 215, 0));
        jLabel29.setText("16");
        add(jLabel29);
        jLabel29.setBounds(269, 2, 42, 17);

        jLabel30.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 215, 0));
        jLabel30.setText("18");
        add(jLabel30);
        jLabel30.setBounds(415, 2, 42, 17);

        jLabel32.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 215, 0));
        jLabel32.setText("17");
        add(jLabel32);
        jLabel32.setBounds(342, 2, 42, 17);

        jLabel31.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 215, 0));
        jLabel31.setText("12");
        add(jLabel31);
        jLabel31.setBounds(50, 685, 42, 17);

        jLabel33.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 215, 0));
        jLabel33.setText("11");
        add(jLabel33);
        jLabel33.setBounds(123, 685, 42, 17);

        jLabel34.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 215, 0));
        jLabel34.setText("10");
        add(jLabel34);
        jLabel34.setBounds(196, 685, 42, 17);

        jLabel35.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 215, 0));
        jLabel35.setText("9");
        add(jLabel35);
        jLabel35.setBounds(269, 685, 42, 17);

        jLabel36.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 215, 0));
        jLabel36.setText("8");
        jLabel36.setToolTipText("");
        add(jLabel36);
        jLabel36.setBounds(342, 685, 42, 17);

        jLabel37.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 215, 0));
        jLabel37.setText("7");
        add(jLabel37);
        jLabel37.setBounds(415, 685, 42, 17);

        jLabel38.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 215, 0));
        jLabel38.setText("6");
        add(jLabel38);
        jLabel38.setBounds(565, 685, 42, 17);

        jLabel39.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 215, 0));
        jLabel39.setText("5");
        add(jLabel39);
        jLabel39.setBounds(638, 685, 42, 17);

        jLabel40.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 215, 0));
        jLabel40.setText("4");
        add(jLabel40);
        jLabel40.setBounds(711, 685, 42, 17);

        jLabel41.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 215, 0));
        jLabel41.setText("3");
        add(jLabel41);
        jLabel41.setBounds(784, 685, 42, 17);

        jLabel42.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 215, 0));
        jLabel42.setText("2");
        add(jLabel42);
        jLabel42.setBounds(857, 685, 42, 17);

        jLabel43.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 215, 0));
        jLabel43.setText("1");
        add(jLabel43);
        jLabel43.setBounds(930, 685, 42, 17);

        jLabel44.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 215, 0));
        jLabel44.setText("24");
        add(jLabel44);
        jLabel44.setBounds(930, 2, 42, 17);

        jLabel45.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 215, 0));
        jLabel45.setText("23");
        add(jLabel45);
        jLabel45.setBounds(857, 2, 42, 17);

        jLabel46.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 215, 0));
        jLabel46.setText("22");
        add(jLabel46);
        jLabel46.setBounds(784, 2, 42, 17);

        jLabel47.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 215, 0));
        jLabel47.setText("21");
        add(jLabel47);
        jLabel47.setBounds(711, 2, 42, 17);

        jLabel48.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 215, 0));
        jLabel48.setText("20");
        add(jLabel48);
        jLabel48.setBounds(638, 2, 42, 17);

        jLabel51.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText(" 0 - 0");
        add(jLabel51);
        jLabel51.setBounds(478, 300, 60, 30);

        jLabel49.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 215, 0));
        jLabel49.setText("19");
        add(jLabel49);
        jLabel49.setBounds(565, 2, 42, 17);

        jPanel2.setBackground(new java.awt.Color(74, 40, 16));
        jPanel2.setLayout(null);

        jButton2.setBackground(new java.awt.Color(255, 215, 0));
        jButton2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("ٍRD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(0, 320, 49, 30);

        barLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        barLabel1.setForeground(new java.awt.Color(255, 255, 255));
        barLabel1.setText("W: 0");
        barLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(barLabel1);
        barLabel1.setBounds(5, 10, 40, 40);

        barLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        barLabel2.setForeground(new java.awt.Color(255, 255, 255));
        barLabel2.setText("B: 0");
        barLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(barLabel2);
        barLabel2.setBounds(5, 620, 40, 40);

        jButton3.setBackground(new java.awt.Color(255, 215, 0));
        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("BO");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(-2, 240, 52, 30);

        add(jPanel2);
        jPanel2.setBounds(478, 20, 50, 660);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (diceRolled) {
        javax.swing.JOptionPane.showMessageDialog(this, "You already rolled! Make your move first!");
        return;
    }
    currentDice = board.rollDice();
    diceRolled = true;
    jLabel51.setText(" " + currentDice[0] + " - " + currentDice[1]);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void point1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point1MouseClicked
        pointClicked(point1, 1);

    }//GEN-LAST:event_point1MouseClicked

    private void point2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point2MouseClicked
        pointClicked(point2, 2);

    }//GEN-LAST:event_point2MouseClicked

    private void point3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point3MouseClicked
        pointClicked(point3, 3);

    }//GEN-LAST:event_point3MouseClicked

    private void point4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point4MouseClicked
        pointClicked(point4, 4);

    }//GEN-LAST:event_point4MouseClicked

    private void point5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point5MouseClicked
        pointClicked(point5, 5);

    }//GEN-LAST:event_point5MouseClicked

    private void point6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point6MouseClicked
        pointClicked(point6, 6);

    }//GEN-LAST:event_point6MouseClicked

    private void point7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point7MouseClicked
        pointClicked(point7, 7);

    }//GEN-LAST:event_point7MouseClicked

    private void point8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point8MouseClicked
        pointClicked(point8, 8);

    }//GEN-LAST:event_point8MouseClicked

    private void point9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point9MouseClicked
        pointClicked(point9, 9);

    }//GEN-LAST:event_point9MouseClicked

    private void point10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point10MouseClicked
        pointClicked(point10, 10);

    }//GEN-LAST:event_point10MouseClicked

    private void point11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point11MouseClicked
        pointClicked(point11, 11);

    }//GEN-LAST:event_point11MouseClicked

    private void point12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point12MouseClicked
        pointClicked(point12, 12);

    }//GEN-LAST:event_point12MouseClicked

    private void point13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point13MouseClicked
        pointClicked(point13, 13);

    }//GEN-LAST:event_point13MouseClicked

    private void point14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point14MouseClicked
        pointClicked(point14, 14);

    }//GEN-LAST:event_point14MouseClicked

    private void point15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point15MouseClicked
        pointClicked(point15, 15);

    }//GEN-LAST:event_point15MouseClicked

    private void point16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point16MouseClicked
        pointClicked(point16, 16);

    }//GEN-LAST:event_point16MouseClicked

    private void point17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point17MouseClicked
        pointClicked(point17, 17);

    }//GEN-LAST:event_point17MouseClicked

    private void point18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point18MouseClicked
        pointClicked(point18, 18);

    }//GEN-LAST:event_point18MouseClicked

    private void point19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point19MouseClicked
        pointClicked(point19, 19);

    }//GEN-LAST:event_point19MouseClicked

    private void point20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point20MouseClicked
        pointClicked(point20, 20);

    }//GEN-LAST:event_point20MouseClicked

    private void point21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point21MouseClicked
        pointClicked(point21, 21);

    }//GEN-LAST:event_point21MouseClicked

    private void point22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point22MouseClicked
        pointClicked(point22, 22);

    }//GEN-LAST:event_point22MouseClicked

    private void point23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point23MouseClicked
        pointClicked(point23, 23);

    }//GEN-LAST:event_point23MouseClicked

    private void point24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_point24MouseClicked
        pointClicked(point24, 24);

    }//GEN-LAST:event_point24MouseClicked

    private void barLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barLabel1MouseClicked
        if (board.getCurrentPlayer() == 1 && board.getBarPlayer1() > 0) {
    selectedLabel = barLabel1;
    selectedPointIndex = -1; // -1 يعني من البار
    barLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 215, 0), 2));
}
    }//GEN-LAST:event_barLabel1MouseClicked

    private void barLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barLabel2MouseClicked
        if (board.getCurrentPlayer() == 2 && board.getBarPlayer2() > 0) {
    selectedLabel = barLabel2;
    selectedPointIndex = -1;
    barLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 215, 0), 2));
}
    }//GEN-LAST:event_barLabel2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        int player = board.getCurrentPlayer();

if (!board.canBearOff(player)) {
    javax.swing.JOptionPane.showMessageDialog(this, "You can't bear off yet! Move all pieces to your home board first!");
    return;
}

if (selectedLabel == null) {
    javax.swing.JOptionPane.showMessageDialog(this, "Select a piece to bear off first!");
    return;
}

int from = selectedPointIndex - 1;

board.bearOff(from, player);

int fromPieces = Math.abs(board.getPoint(from));
String fromPieceColor = board.getPoint(from) > 0 ? "white" : "black";
updatePointImage(selectedLabel, triColors[from], fromPieces == 0 ? "white" : fromPieceColor, fromPieces, flippedPoints[from]);

selectedLabel.setBorder(null);
selectedLabel = null;
selectedPointIndex = -1;
board.switchPlayer();
diceRolled = false;

if (board.hasWon(player)) {
    String winner = player == 1 ? "White ⚪" : "Black ⚫";
    int choice = javax.swing.JOptionPane.showConfirmDialog(this, 
        winner + " wins!\nPlay again?", 
        "Game Over", 
        javax.swing.JOptionPane.YES_NO_OPTION);
    if (choice == javax.swing.JOptionPane.YES_OPTION) {
        // نرجع لشاشة البداية
        javax.swing.JFrame frame = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        frame.getContentPane().removeAll();
        frame.getContentPane().add(new BoardPanel());
        frame.revalidate();
        frame.repaint();
    } else {
        System.exit(0);
    }
}
    }//GEN-LAST:event_jButton3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barLabel1;
    private javax.swing.JLabel barLabel2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel point1;
    private javax.swing.JLabel point10;
    private javax.swing.JLabel point11;
    private javax.swing.JLabel point12;
    private javax.swing.JLabel point13;
    private javax.swing.JLabel point14;
    private javax.swing.JLabel point15;
    private javax.swing.JLabel point16;
    private javax.swing.JLabel point17;
    private javax.swing.JLabel point18;
    private javax.swing.JLabel point19;
    private javax.swing.JLabel point2;
    private javax.swing.JLabel point20;
    private javax.swing.JLabel point21;
    private javax.swing.JLabel point22;
    private javax.swing.JLabel point23;
    private javax.swing.JLabel point24;
    private javax.swing.JLabel point3;
    private javax.swing.JLabel point4;
    private javax.swing.JLabel point5;
    private javax.swing.JLabel point6;
    private javax.swing.JLabel point7;
    private javax.swing.JLabel point8;
    private javax.swing.JLabel point9;
    // End of variables declaration//GEN-END:variables



public void pointClicked(javax.swing.JLabel label, int pointIndex) {
    
    if (selectedLabel != null) {
        selectedLabel.setBorder(null);
    }
    
    if (selectedLabel == label) {
        selectedLabel = null;
        selectedPointIndex = -1;
        return;
    }
    
    if (selectedLabel != null) {
        
        if (!diceRolled) {
            javax.swing.JOptionPane.showMessageDialog(this, "Roll the dice first!");
            selectedLabel = null;
            selectedPointIndex = -1;
            return;
        }
        
        int to = pointIndex - 1;
        int player = board.getCurrentPlayer();
        
        // لو اللاعب جاي من البار
        if (selectedPointIndex == -1) {
            
            // تحقق لو كل المكانين مبلوكين
            if (player == 1) {
                boolean allBlocked = true;
                for (int i = 18; i < 24; i++) {
                    if (board.canEnterFromBar(i, player)) {
                        allBlocked = false;
                        break;
                    }
                }
                if (allBlocked) {
                    javax.swing.JOptionPane.showMessageDialog(this, "All entry points are blocked! Turn lost!");
                    selectedLabel.setBorder(null);
                    selectedLabel = null;
                    selectedPointIndex = -1;
                    board.switchPlayer();
                    diceRolled = false;
                    return;
                }
            } else {
                boolean allBlocked = true;
                for (int i = 0; i < 6; i++) {
                    if (board.canEnterFromBar(i, player)) {
                        allBlocked = false;
                        break;
                    }
                }
                if (allBlocked) {
                    javax.swing.JOptionPane.showMessageDialog(this, "All entry points are blocked! Turn lost!");
                    selectedLabel.setBorder(null);
                    selectedLabel = null;
                    selectedPointIndex = -1;
                    board.switchPlayer();
                    diceRolled = false;
                    return;
                }
            }
            
            if (player == 1) {
                if (to < 18) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Enter from the Bar into points 19-24!");
                    selectedLabel.setBorder(null);
                    selectedLabel = null;
                    selectedPointIndex = -1;
                    return;
                }
            } else {
                if (to > 5) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Enter from the Bar into points 1-6!");
                    selectedLabel.setBorder(null);
                    selectedLabel = null;
                    selectedPointIndex = -1;
                    return;
                }
            }
            
            // تحقق من النرد
            int diff = player == 1 ? (23 - to) : to;
            if (Math.abs(diff) != currentDice[0] && Math.abs(diff) != currentDice[1]) {
                javax.swing.JOptionPane.showMessageDialog(this, "Invalid move! Use dice numbers: " + currentDice[0] + " or " + currentDice[1]);
                selectedLabel.setBorder(null);
                selectedLabel = null;
                selectedPointIndex = -1;
                return;
            }
            
            // تحقق من المكان مش مسكور
            if (!board.canEnterFromBar(to, player)) {
                javax.swing.JOptionPane.showMessageDialog(this, "This point is blocked by your opponent!");
                selectedLabel.setBorder(null);
                selectedLabel = null;
                selectedPointIndex = -1;
                return;
            }
            
            board.enterFromBar(to, player);
            barLabel1.setText("W: " + board.getBarPlayer1());
            barLabel2.setText("B: " + board.getBarPlayer2());
            int toPieces = Math.abs(board.getPoint(to));
            String toPieceColor = board.getPoint(to) > 0 ? "white" : "black";
            updatePointImage(label, triColors[to], toPieces == 0 ? "white" : toPieceColor, toPieces, flippedPoints[to]);
            selectedLabel.setBorder(null);
            selectedLabel = null;
            selectedPointIndex = -1;
            board.switchPlayer();
            diceRolled = false;
            
            if (board.hasWon(player)) {
                String winner = player == 1 ? "White ⚪" : "Black ⚫";
                int choice = javax.swing.JOptionPane.showConfirmDialog(this, 
                    winner + " wins!\nPlay again?", 
                    "Game Over", 
                    javax.swing.JOptionPane.YES_NO_OPTION);
                if (choice == javax.swing.JOptionPane.YES_OPTION) {
                    javax.swing.JFrame frame = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
                    frame.getContentPane().removeAll();
                    frame.getContentPane().add(new BoardPanel());
                    frame.revalidate();
                    frame.repaint();
                } else {
                    System.exit(0);
                }
            }
            
            return;
        }
        
        int from = selectedPointIndex - 1;
        
        if (player == 1 && board.getBarPlayer1() > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "You have pieces on the Bar! Enter them first!");
            selectedLabel = null;
            selectedPointIndex = -1;
            return;
        }
        if (player == 2 && board.getBarPlayer2() > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "You have pieces on the Bar! Enter them first!");
            selectedLabel = null;
            selectedPointIndex = -1;
            return;
        }
        
        if (player == 1 && board.getPoint(from) <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "It's White's Turn! Move your white pieces!");
            selectedLabel = null;
            selectedPointIndex = -1;
            return;
        }
        if (player == 2 && board.getPoint(from) >= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "It's Black's Turn! Move your black pieces!");
            selectedLabel = null;
            selectedPointIndex = -1;
            return;
        }
        
        if (!board.isValidMove(from, to, player)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid move! Point is blocked or full!");
            selectedLabel = null;
            selectedPointIndex = -1;
            return;
        }
        
        if (player == 1 && to >= from) {
            javax.swing.JOptionPane.showMessageDialog(this, "White moves from 24 to 1!");
            selectedLabel = null;
            selectedPointIndex = -1;
            return;
        }
        if (player == 2 && to <= from) {
            javax.swing.JOptionPane.showMessageDialog(this, "Black moves from 1 to 24!");
            selectedLabel = null;
            selectedPointIndex = -1;
            return;
        }
        
        int diff;
        if (player == 1) {
            diff = from - to;
        } else {
            diff = to - from;
        }
        if (Math.abs(diff) != currentDice[0] && Math.abs(diff) != currentDice[1]) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid move! Use dice numbers: " + currentDice[0] + " or " + currentDice[1]);
            selectedLabel = null;
            selectedPointIndex = -1;
            return;
        }
        
        board.movePiece(from, to, player);
        
        if (gameClient != null) {
            gameClient.sendMove(from, to);
        }
        
        barLabel1.setText("W: " + board.getBarPlayer1());
        barLabel2.setText("B: " + board.getBarPlayer2());
        
        int fromPieces = Math.abs(board.getPoint(from));
        String fromPieceColor = board.getPoint(from) > 0 ? "white" : "black";
        updatePointImage(selectedLabel, triColors[from], fromPieces == 0 ? "white" : fromPieceColor, fromPieces, flippedPoints[from]);
        
        int toPieces = Math.abs(board.getPoint(to));
        String toPieceColor = board.getPoint(to) > 0 ? "white" : "black";
        updatePointImage(label, triColors[to], toPieces == 0 ? "white" : toPieceColor, toPieces, flippedPoints[to]);
        
        board.switchPlayer();
        diceRolled = false;
        
        if (board.hasWon(player)) {
            String winner = player == 1 ? "White ⚪" : "Black ⚫";
            int choice = javax.swing.JOptionPane.showConfirmDialog(this, 
                winner + " wins!\nPlay again?", 
                "Game Over", 
                javax.swing.JOptionPane.YES_NO_OPTION);
            if (choice == javax.swing.JOptionPane.YES_OPTION) {
                javax.swing.JFrame frame = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
                frame.getContentPane().removeAll();
                frame.getContentPane().add(new BoardPanel());
                frame.revalidate();
                frame.repaint();
            } else {
                System.exit(0);
            }
        }
        
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (window instanceof javax.swing.JFrame) {
            ((javax.swing.JFrame) window).setTitle(
                board.getCurrentPlayer() == 1 ? 
                "Backgammon - White's Turn ⚪" : 
                "Backgammon - Black's Turn ⚫"
            );
        }
        
        selectedLabel = null;
        selectedPointIndex = -1;
        return;
    }
    
    selectedLabel = label;
    selectedPointIndex = pointIndex;
    label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 215, 0), 2));
}
public void updatePointImage(javax.swing.JLabel label, String triColor, String pieceColor, int pieces, boolean flipped) {
    String flippedStr = flipped ? "_flipped" : "";
    String path = "/images/triangle_" + triColor + "_" + pieceColor + "_" + pieces + flippedStr + ".png";
    java.net.URL imgURL = getClass().getResource(path);
    if (imgURL != null) {
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
java.awt.Image img = icon.getImage().getScaledInstance(label.getWidth(), label.getHeight(), java.awt.Image.SCALE_SMOOTH);
label.setIcon(new javax.swing.ImageIcon(img));
    } else {
        System.out.println("IMAGE NOT FOUND: " + path);
    }
}

public void applyOpponentMove(int from, int to) {
    board.movePiece(from, to, board.getCurrentPlayer());
    
    barLabel1.setText("W: " + board.getBarPlayer1());
    barLabel2.setText("B: " + board.getBarPlayer2());
    
    int fromPieces = Math.abs(board.getPoint(from));
    String fromPieceColor = board.getPoint(from) > 0 ? "white" : "black";
    
    int toPieces = Math.abs(board.getPoint(to));
    String toPieceColor = board.getPoint(to) > 0 ? "white" : "black";
    
    // هنحدث الصور بعدين
    board.switchPlayer();
}

public void setGameClient(GameClient client) {
    this.gameClient = client;
}


}
