/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package client;

/**
 *
 * @author saadrady
 */
public class GamePanel extends javax.swing.JPanel {

    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(92, 61, 30));
        setToolTipText("255");
        setLayout(null);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 215, 0));
        jLabel7.setText("13");
        add(jLabel7);
        jLabel7.setBounds(50, 2, 42, 17);

        jPanel3.setBackground(new java.awt.Color(46, 125, 50));
        jPanel3.setLayout(null);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_black_5.png"))); // NOI18N
        jPanel3.add(jLabel13);
        jLabel13.setBounds(5, 0, 70, 250);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_0.png"))); // NOI18N
        jPanel3.add(jLabel14);
        jLabel14.setBounds(78, 0, 70, 250);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_white_0.png"))); // NOI18N
        jPanel3.add(jLabel16);
        jLabel16.setBounds(151, 0, 70, 250);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_0.png"))); // NOI18N
        jPanel3.add(jLabel15);
        jLabel15.setBounds(224, 0, 70, 250);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_white_0.png"))); // NOI18N
        jPanel3.add(jLabel17);
        jLabel17.setBounds(297, 0, 70, 250);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_2.png"))); // NOI18N
        jPanel3.add(jLabel18);
        jLabel18.setBounds(370, 0, 70, 250);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_5_flipped.png"))); // NOI18N
        jPanel3.add(jLabel19);
        jLabel19.setBounds(5, 410, 70, 250);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_white_0_flipped.png"))); // NOI18N
        jPanel3.add(jLabel20);
        jLabel20.setBounds(78, 410, 70, 250);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_0_flipped.png"))); // NOI18N
        jPanel3.add(jLabel21);
        jLabel21.setBounds(151, 410, 70, 250);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_white_0_flipped.png"))); // NOI18N
        jPanel3.add(jLabel22);
        jLabel22.setBounds(224, 410, 70, 250);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_0_flipped.png"))); // NOI18N
        jPanel3.add(jLabel23);
        jLabel23.setBounds(297, 410, 70, 250);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_black_2_flipped.png"))); // NOI18N
        jPanel3.add(jLabel24);
        jLabel24.setBounds(370, 410, 70, 250);

        add(jPanel3);
        jPanel3.setBounds(530, 20, 455, 660);

        jLabel26.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 215, 0));
        jLabel26.setText("14");
        add(jLabel26);
        jLabel26.setBounds(123, 2, 42, 17);

        jPanel1.setBackground(new java.awt.Color(46, 125, 50));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_0.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(78, 0, 70, 250);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_white_0.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(151, 0, 70, 250);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_0.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(224, 0, 70, 250);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_black_3.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(297, 0, 70, 250);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_0.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(370, 0, 70, 250);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_black_5_flipped.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(5, 410, 70, 250);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_white_0_flipped.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(78, 410, 70, 250);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_0_flipped.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(151, 410, 70, 250);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_white_0_flipped.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(224, 410, 70, 250);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_white_white_3_flipped.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(297, 410, 70, 250);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_white_0_flipped.png"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(370, 410, 70, 250);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/triangle_red_white_5.png"))); // NOI18N
        jPanel1.add(jLabel25);
        jLabel25.setBounds(5, 0, 70, 250);

        jLabel28.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 215, 0));
        jLabel28.setText("16");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(269, 2, 42, 17);

        add(jPanel1);
        jPanel1.setBounds(20, 20, 455, 660);

        jLabel27.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 215, 0));
        jLabel27.setText("15");
        add(jLabel27);
        jLabel27.setBounds(196, 2, 42, 17);

        jLabel29.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 215, 0));
        jLabel29.setText("16");
        add(jLabel29);
        jLabel29.setBounds(269, 2, 42, 17);

        jLabel30.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 215, 0));
        jLabel30.setText("18");
        add(jLabel30);
        jLabel30.setBounds(415, 2, 42, 17);

        jLabel32.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 215, 0));
        jLabel32.setText("17");
        add(jLabel32);
        jLabel32.setBounds(342, 2, 42, 17);

        jLabel31.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 215, 0));
        jLabel31.setText("12");
        add(jLabel31);
        jLabel31.setBounds(50, 685, 42, 17);

        jLabel33.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 215, 0));
        jLabel33.setText("11");
        add(jLabel33);
        jLabel33.setBounds(123, 685, 42, 17);

        jLabel34.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 215, 0));
        jLabel34.setText("10");
        add(jLabel34);
        jLabel34.setBounds(196, 685, 42, 17);

        jLabel35.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 215, 0));
        jLabel35.setText("9");
        add(jLabel35);
        jLabel35.setBounds(269, 685, 42, 17);

        jLabel36.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 215, 0));
        jLabel36.setText("8");
        jLabel36.setToolTipText("");
        add(jLabel36);
        jLabel36.setBounds(342, 685, 42, 17);

        jLabel37.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 215, 0));
        jLabel37.setText("7");
        add(jLabel37);
        jLabel37.setBounds(415, 685, 42, 17);

        jLabel38.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 215, 0));
        jLabel38.setText("6");
        add(jLabel38);
        jLabel38.setBounds(565, 685, 42, 17);

        jLabel39.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 215, 0));
        jLabel39.setText("5");
        add(jLabel39);
        jLabel39.setBounds(638, 685, 42, 17);

        jLabel40.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 215, 0));
        jLabel40.setText("4");
        add(jLabel40);
        jLabel40.setBounds(711, 685, 42, 17);

        jLabel41.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 215, 0));
        jLabel41.setText("3");
        add(jLabel41);
        jLabel41.setBounds(784, 685, 42, 17);

        jLabel42.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 215, 0));
        jLabel42.setText("2");
        add(jLabel42);
        jLabel42.setBounds(857, 685, 42, 17);

        jLabel43.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 215, 0));
        jLabel43.setText("1");
        add(jLabel43);
        jLabel43.setBounds(930, 685, 42, 17);

        jLabel44.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 215, 0));
        jLabel44.setText("24");
        add(jLabel44);
        jLabel44.setBounds(930, 2, 42, 17);

        jLabel45.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 215, 0));
        jLabel45.setText("23");
        add(jLabel45);
        jLabel45.setBounds(857, 2, 42, 17);

        jLabel46.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 215, 0));
        jLabel46.setText("22");
        add(jLabel46);
        jLabel46.setBounds(784, 2, 42, 17);

        jLabel47.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 215, 0));
        jLabel47.setText("21");
        add(jLabel47);
        jLabel47.setBounds(711, 2, 42, 17);

        jLabel48.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 215, 0));
        jLabel48.setText("20");
        add(jLabel48);
        jLabel48.setBounds(638, 2, 42, 17);

        jLabel51.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText(" 0 - 0");
        add(jLabel51);
        jLabel51.setBounds(478, 300, 60, 30);

        jLabel49.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 215, 0));
        jLabel49.setText("19");
        add(jLabel49);
        jLabel49.setBounds(565, 2, 42, 17);

        jPanel2.setBackground(new java.awt.Color(74, 40, 16));
        jPanel2.setLayout(null);

        jButton2.setBackground(new java.awt.Color(255, 215, 0));
        jButton2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("ٍRD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(0, 320, 49, 30);

        add(jPanel2);
        jPanel2.setBounds(478, 20, 50, 660);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        game.BackgammonBoard board = new game.BackgammonBoard();
int[] dice = board.rollDice();
jLabel51.setText(" " + dice[0] + " - " + dice[1]);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
